[package]
name = "ai-coder"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["dialog-open", "shell-open"] }

[build-dependencies]
